spring.application.name=secondrest_se2421
spring.datasource.url=jdbc:postgresql://localhost:5432/zoo_db
spring.datasource.username=postgres
spring.datasource.password=0528bal
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
server.port=9090